/* =====================================================================
   data.js — ALL default content for the May 2027 trip planner.

   This file assigns one global object, window.TRIP_DATA. app.js copies
   it into localStorage on first load (or after "Reset to defaults").

   HAND-EDITING TIPS
   - Edits here only show up in the browser after you click
     "Reset to defaults" (or clear localStorage), because saved edits
     take priority over this file. Export JSON first if you want to
     keep browser edits.
   - Scores are 1–5. Cost tier: 1 = cheap … 5 = Switzerland.
   - Put the token [verify] anywhere in a text field and the UI renders
     a visible "verify" tag. The per-option `verify` array is the
     canonical list of things that need checking.
   - To add a bucket: copy one of the bucket objects below, give it a
     new unique `id`, and add it to the `buckets` array. To add a
     sub-option: copy one of the `subOptions` objects. Every field is
     optional except id/name, but the Compare grid expects the numeric
     ones.

   FIELD REFERENCE (sub-option)
     id, name, bases        strings
     type                   city | mountains | mixed | coast
     costTier               1–5
     flightHours            total hours IAD/DCA -> gateway, nonstop or typical connection
     direct                 yes | seasonal | no   (nonstop to the gateway airport)
     connectionCostsDay     yes | no  — does the connection cost a full travel day?
                            (only then does a missing nonstop get the big travel penalty)
     flightNote             text
     train                  yes | partial | no    (inter-base leg by train)
     trainHours             number
     trainNote              text
     car                    none | optional | needed
     carNote                text
     rail                   1–5 overall rail-friendliness (used for scoring)
     kid3, kid7             1–5
     scenery, history       1–5
     beach                  yes | limited | no
     beachHow               text
     lodgingStyle           text (one big house vs hotels/apartments)
     lodging57              text (how 5 vs 7 people changes it)
     weather                text (expected May weather)
     notes                  text
     openQuestions          [string]
     todos                  [{text, done}]
     verify                 [string]
     status                 idea | researching | shortlisted | rejected
     statusReason           text
     detail                 optional day-by-day plan: { arrival, lodging, days7[], days10[],
                            anchorsKids, anchorsAdults, mayWeek, verify[] }. Rendered as
                            the "Plan" section and the "Has plan" badge.
   ===================================================================== */

window.TRIP_DATA = {
  version: 4,

  meta: {
    title: "May 2027 family trip",
    tagline: "7–10 days, ~2 bases, trains first, towns and scenery over box-ticking",
    travelers: [
      "Alex and Caresse",
      "Simon (7) and Penny (3) — can miss school",
      "Melissa",
      "Maybe Jeremy — known early 2027",
    ],
    groupSize: "5, or 7 with Jeremy",
    homeAirports: "IAD / DCA (DCA has no transatlantic flights, so IAD in practice)",
    dates: "TBD inside May 2027; settled early 2027. Memorial Day is Mon May 31, 2027.",
    preferences: [
      "City-centric, ~2 bases. A beach day is welcome but not the point.",
      "Trains for the inter-base leg and local travel. 'Doable fully by rail' is a major plus.",
      "Driving (incl. on the left) is fine when it unlocks something.",
      "Alps: scenery and towns first, accessible day hikes welcome.",
      "Cost is a tiebreaker, not a constraint.",
    ],
  },

  /* Default criteria weights (0–5). Rail/kid/scenery/history high,
     travel time and beach medium, cost near zero. */
  weights: {
    rail: 5,
    kid: 4,
    scenery: 4,
    history: 4,
    travel: 2.5,
    beach: 2,
    cost: 0.5,
  },

  buckets: [
    /* ================================================================
       1. SPAIN / PORTUGAL
       ================================================================ */
    {
      id: "iberia",
      name: "Spain / Portugal",
      type: "mixed",
      costTier: 2,
      railScore: 4,
      status: "researching",
      statusReason: "Cheapest, sunniest, and Lisbon has a nonstop. Needs a decision on how much beach we want.",
      why: "Nonstop to Lisbon, the most reliable May weather on the board, walkable old cities, easy beach days, and good intercity rail (Alfa Pendular, AVE).",
      whyNot: "Least novel for the history crowd; the Algarve variant pushes you into a car; Seville can already be hot by late May.",
      notes: "",
      openQuestions: [
        "How much beach do we actually want? Lisbon+Porto is a city trip with a beach afternoon; Lisbon+Algarve is half beach.",
        "Portugal vs. Spain — or one base in each (Lisbon + Seville is ~6h by bus/train with a change; not a clean rail leg)?",
      ],
      todos: [
        { text: "Check whether United still flies IAD–LIS and IAD–OPO (seasonal) for May 2027", done: false },
        { text: "Check TAP IAD–LIS schedule", done: false },
      ],
      subOptions: [
        {
          id: "lisbon-porto",
          name: "Lisbon + Porto",
          bases: "Lisbon (4–5 nights) → Porto (3–4 nights)",
          type: "city",
          costTier: 2,
          flightHours: 7.5,
          direct: "yes",
          connectionCostsDay: "no",
          flightNote: "IAD–LIS nonstop (United, TAP) ~7.5h [verify]. United has run a seasonal IAD–OPO nonstop in summer — if it starts by May, fly open-jaw and skip the backtrack [verify].",
          train: "yes",
          trainHours: 3,
          trainNote: "Alfa Pendular Lisbon Santa Apolónia/Oriente → Porto Campanhã ~3h, roughly hourly [verify]. Book ~60 days out on cp.pt.",
          car: "none",
          carNote: "Everything by metro, tram, suburban train and foot. Hills and cobbles are stroller-hostile — bring a carrier for Penny.",
          rail: 5,
          kid3: 4,
          kid7: 4,
          scenery: 4,
          history: 3,
          beach: "yes",
          beachHow: "Cascais / Carcavelos by suburban train from Cais do Sodré (~40 min). From Porto, Matosinhos beach by metro. Atlantic is cold (~62°F) — sandcastles, not swimming.",
          lodgingStyle: "Apartments in both cities (Alfama / Chiado / Príncipe Real; Porto Ribeira / Cedofeita).",
          lodging57: "5 = one 3BR apartment is easy. 7 = 4BR in central Lisbon is scarce and pricey; more realistic is two adjacent apartments or an aparthotel. Porto similar but cheaper.",
          weather: "Lisbon highs ~72°F, cool evenings, mostly sunny. Porto a few degrees cooler with occasional showers.",
          notes: "Sintra (Pena Palace, Quinta da Regaleira) is a 40-min train day trip — timed tickets, go early. Lisbon: Tram 28, Oceanário, Belém pastéis, Time Out Market. Porto: Douro boat, Gaia cable car, Livraria Lello, port lodges (kids get juice). Could do Sintra as a one-night mini-base instead of a day trip.",
          openQuestions: [
            "Open-jaw (into LIS, out of OPO) or round trip from Lisbon?",
            "Sintra as a day trip or a one-night stop?",
          ],
          todos: [
            { text: "Confirm United IAD–OPO 2027 season start date", done: false },
            { text: "Look at 4BR apartment inventory in Lisbon for a May week", done: false },
          ],
          verify: [
            "IAD–LIS nonstop schedule for May 2027 (United, TAP)",
            "IAD–OPO seasonal nonstop start date",
            "Alfa Pendular timetable and booking window",
            "Pena Palace timed-ticket rules",
            "IAD–LIS and IAD–OPO nonstop schedules for May 2027",
            "Alfa Pendular booking window",
            "Pena Palace and Lello timed-ticket rules",
            "Sintra/Cascais villa inventory for 7",
            "Douro line (Pinhão) timetable",
          ],
          detail: {
            arrival: "IAD–LIS nonstop (United/TAP), overnight, land ~morning [verify]. Metro or taxi into town (20 min). Open-jaw out of Porto if United's seasonal IAD–OPO runs by May [verify]; otherwise Alfa Pendular back to Lisbon (3h) the last morning.",
            lodging: "Lisbon: a 3–4BR apartment in Chiado/Príncipe Real or Martinhal Chiado (an aparthotel built for families, with a kids' club). Alternative base in Sintra or Cascais — villas with pools sleeping 7, 40 min by train to the city, and the beach day comes free. Porto: Ribeira/Cedofeita apartments or a Foz villa.",
            days7: [
              "D1 Land LIS. Belém: pastéis, Monument to the Discoveries, MAAT riverside walk; early night.",
              "D2 Alfama: Tram 28 early, castle São Jorge (peacocks, ramparts), miradouros, Fado-free early dinner. Oceanário in the afternoon if the kids need air-con.",
              "D3 Sintra day: Pena Palace at opening (timed ticket), Quinta da Regaleira initiation well, Cabo da Roca sunset if energy holds.",
              "D4 Beach day: train to Cascais, Praia da Rainha / Guincho by bus, ice cream at Santini. Or Carcavelos for the big sandy beach.",
              "D5 Alfa Pendular to Porto (3h, book 60 days out). Ribeira walk, Dom Luís bridge top deck, Gaia cable car, sunset on the Gaia side.",
              "D6 Porto: Livraria Lello (timed), São Bento tiles, Douro six-bridges boat, port lodge tour with juice for the kids, francesinha for the brave.",
              "D7 Douro Valley by train to Pinhão (2h20 along the river, sit on the right), rabelo boat, back by late afternoon. Or Foz do Douro tram + Matosinhos beach.",
              "D8 Fly home from OPO (if nonstop) or train to Lisbon + evening flight [verify].",
            ],
            days10: [
              "5 nights Lisbon/Sintra + 5 nights Porto.",
              "Extra Lisbon days: Óbidos walled town + Nazaré (big waves, funicular) as a day; Lisbon Zoo; Setúbal dolphins boat; a second Sintra day for Monserrate.",
              "Extra Porto days: Guimarães (birthplace of Portugal, castle, 1h by train); Aveiro canals + Costa Nova striped houses; Braga + Bom Jesus funicular (water-powered).",
              "Option: make Sintra a 2-night base between Lisbon and Porto to break the city stretch.",
            ],
            anchorsKids: "Tram 28, castle peacocks, Oceanário, Pena Palace, Regaleira well, beach, Gaia cable car, Douro boat, Nazaré funicular.",
            anchorsAdults: "Alfama, Belém, Sintra, Ribeira, port lodges, Douro train.",
            mayWeek: "Any week; Lisbon highs ~72°F, Porto a touch cooler. Sintra and Lello timed tickets are the only crowd issue. Atlantic ~62°F — a sand day, not a swim day.",
            verify: [
              "IAD–LIS and IAD–OPO nonstop schedules for May 2027",
              "Alfa Pendular booking window",
              "Pena Palace and Lello timed-ticket rules",
              "Sintra/Cascais villa inventory for 7",
              "Douro line (Pinhão) timetable",
            ],
          },
          status: "shortlisted",
          statusReason: "Shortlisted 2026-10-03 with a detailed plan (see Plan below). Strongest fully-rail option in the bucket.",
        },
        {
          id: "lisbon-algarve",
          name: "Lisbon + Algarve",
          bases: "Lisbon (4 nights) → Lagos or Tavira (4–5 nights)",
          type: "mixed",
          costTier: 2,
          flightHours: 7.5,
          direct: "yes",
          connectionCostsDay: "no",
          flightNote: "IAD–LIS nonstop ~7.5h [verify]. Faro has no US nonstops; the train from Lisbon is the connection.",
          train: "yes",
          trainHours: 3.5,
          trainNote: "Lisbon Oriente → Faro IC/AP ~3h, then regional to Lagos ~1h45 or Tavira ~35 min [verify]. Lagos and Tavira stations are walkable to town.",
          car: "optional",
          carNote: "Towns are walkable, but beach-hopping, Benagil caves and Sagres want a car. Rent at Faro or Lagos for the Algarve half only. 7 people = minivan.",
          rail: 4,
          kid3: 5,
          kid7: 5,
          scenery: 4,
          history: 2,
          beach: "yes",
          beachHow: "Lagos (Meia Praia, Praia Dona Ana), Tavira island by ferry. Water ~64°F late May — the kids will swim, the adults will wade.",
          lodgingStyle: "Lisbon apartment, then a villa with a pool in the Algarve (easy to find).",
          lodging57: "7 is actually easier here than in the cities: 4–5BR villas with pools are standard Algarve stock. Ask about pool heating in May.",
          weather: "Algarve highs mid-70s°F, the sunniest corner of Europe in May. Lisbon ~72°F.",
          notes: "May is before peak — prices and crowds are lower. Zoomarine (Albufeira) is a kid magnet. Benagil cave by boat/kayak. Lagos–Sagres bus for the end-of-the-world cliffs. Tavira is the quieter, prettier choice; Lagos has more to do.",
          openQuestions: [
            "Does a half-beach trip violate 'beach is not the point'?",
            "Lagos (lively, dramatic coast) vs. Tavira (quiet, flat, old town)?",
          ],
          todos: [
            { text: "Check regional train frequency Faro–Lagos", done: false },
          ],
          verify: [
            "Lisbon–Faro and Faro–Lagos train times",
            "Villa pool heating in May",
            "Benagil tour operators and kid age limits",
            "IAD–LIS nonstop schedule May 2027",
            "Villa heated pool",
            "Benagil tour operators and age limits",
            "Faro → home connection options",
          ],
          detail: {
            arrival: "IAD–LIS nonstop, overnight, land ~morning [verify]. Metro or taxi into town. Start in Lisbon, train south mid-trip. Fly home from Lisbon (train back 3h the last morning) or from Faro via a connection [verify].",
            lodging: "Lisbon: a 3–4BR apartment in Chiado / Príncipe Real or the Martinhal Chiado family aparthotel. Algarve: a villa with a heated pool near Lagos (Praia da Luz, Meia Praia) or in Tavira — 4–5BR villas are standard stock and May is pre-season, so 7 is easy and cheap. Rental car for the Algarve half from Faro or Lagos (7 = minivan).",
            days7: [
              "D1 Land LIS. Belém: pastéis, tower, riverside walk; early night.",
              "D2 Alfama: Tram 28 early, Castelo de São Jorge, miradouros; Oceanário in the afternoon if it is hot.",
              "D3 Sintra: Pena Palace at opening, Quinta da Regaleira — or a Cascais beach day with Boca do Inferno.",
              "D4 Train Lisbon Oriente → Faro (3h), then pick up the car, or regional train to Lagos (1h45) / Tavira (35 min) [verify]. Villa, pool, sunset.",
              "D5 Lagos: Ponta da Piedade boardwalks + grotto boat (small boats, calm sea), Praia Dona Ana, old town. Tavira version: ferry to Ilha de Tavira, Roman bridge, camera obscura.",
              "D6 Benagil cave by boat or kayak from Carvoeiro / Portimão (book a kid-friendly skipper), a short stretch of the Seven Hanging Valleys trail, Carvoeiro boardwalk. Or Zoomarine for a full kid day.",
              "D7 Sagres and Cabo de São Vicente (fortress, end-of-the-world cliffs, Praia do Beliche); or Silves castle + Monchique hills — or simply the pool.",
              "D8 Drive to Faro (1h) and fly via Lisbon, or train to Lisbon (3h) for an evening flight [verify].",
            ],
            days10: [
              "4 nights Lisbon (add Óbidos + Nazaré day, Setúbal dolphins boat, Guincho) + 5–6 nights Algarve.",
              "Extra Algarve: Ria Formosa lagoon boat from Olhão with flamingos, Alte village and waterfalls, Loulé Saturday market, ferry to Ayamonte in Spain from Vila Real de Santo António.",
              "Option: 2 nights Évora (UNESCO town, bone chapel, 1h30 by train) between Lisbon and the Algarve.",
            ],
            anchorsKids: "Tram 28, Pena Palace, Oceanário, the villa pool, Ponta da Piedade boats, Benagil cave, the Ilha de Tavira ferry, Zoomarine, Sagres cliffs.",
            anchorsAdults: "Alfama, Sintra, Algarve cliff walks, cataplana and grilled fish, Sagres sunset.",
            mayWeek: "Any week; Algarve highs mid-70s, sea 63–65°F (late May a touch warmer). Pre-season means cheaper villas and empty beaches, but some beach restaurants are not yet open in early May [verify]. Pool heating is essential.",
            verify: [
              "IAD–LIS nonstop schedule May 2027",
              "Lisbon–Faro and Faro–Lagos train times",
              "Villa heated pool",
              "Benagil tour operators and age limits",
              "Faro → home connection options",
            ],
          },
          status: "shortlisted",
          statusReason: "Shortlisted 2026-10-03 (top ten) with a detailed plan. Kid-friendliest Iberia variant but tilts toward beach.",
        },
        {
          id: "seville-granada",
          name: "Seville + Granada (or Cádiz)",
          bases: "Seville (4 nights) → Granada (3 nights) — or Cádiz for a sea version",
          type: "city",
          costTier: 2,
          flightHours: 9.5,
          direct: "no",
          connectionCostsDay: "no",
          flightNote: "No nonstop to Seville. Best: IAD–MAD nonstop (United/Iberia ~8h [verify]) then AVE Madrid–Seville 2.5h — the train leg is part of the fun. Or connect via LIS/LHR.",
          train: "yes",
          trainHours: 2.5,
          trainNote: "Seville–Granada direct train ~2.5–3h (Avant/AVE, since 2019) [verify]. Seville–Cádiz regional ~1h40. Córdoba is a 45-min AVE stop between Madrid and Seville.",
          car: "none",
          carNote: "Not needed. Granada → Costa Tropical beaches would need a bus or car (~1h).",
          rail: 5,
          kid3: 3,
          kid7: 4,
          scenery: 4,
          history: 5,
          beach: "yes",
          beachHow: "Only if Cádiz is the second base: Playa de la Caleta / Playa Victoria right in town. From Granada it's a trek.",
          lodgingStyle: "Apartments in Santa Cruz / Triana (Seville) and Albaicín / Realejo (Granada); hotels are good value.",
          lodging57: "4BR apartments exist in Seville; in Granada look for a carmen house in the Albaicín. 7 is doable with two apartments.",
          weather: "Seville highs 80–88°F, late May can spike past 95°F. Granada ~75°F with snow still on the Sierra Nevada. Cádiz ~73°F with sea breeze.",
          notes: "Alhambra tickets sell out months ahead — book the day 2027 dates are fixed. Real Alcázar (Game of Thrones for Simon), Plaza de España rowboats, Isla Mágica theme park, flamenco at a tablao with early show. Córdoba's Mezquita fits as a stop. Feria de Abril 2027 should fall in mid/late April (two weeks after Easter, Mar 28) — before May [verify].",
          openQuestions: [
            "Granada (history, Alhambra) vs. Cádiz (beach, seafood, oldest city in Western Europe)?",
            "Add Córdoba as a stop on the AVE?",
            "Early May only — late May heat in Seville with Penny?",
          ],
          todos: [
            { text: "Check Alhambra ticket release timing", done: false },
            { text: "Check IAD–MAD nonstop schedule", done: false },
          ],
          verify: [
            "IAD–MAD nonstop schedule",
            "Seville–Granada direct train times",
            "Alhambra ticket release window",
            "Feria de Abril 2027 dates",
            "IAD–MAD nonstop schedule May 2027",
            "AVE Madrid–Seville and Seville–Granada timetables",
            "Alhambra ticket release and Nasrid Palaces slots",
            "Córdoba patios festival 2027 dates",
            "Sierra Nevada access in May",
          ],
          detail: {
            arrival: "IAD–MAD nonstop, overnight, land ~morning [verify]. Cercanías C1 from Terminal 4 to Atocha (~25 min), then AVE Madrid → Seville 2h30 — you are in Seville by mid-afternoon the same day. The train is part of the fun: book a table of four. Fly home from Madrid again (Granada → Madrid AVE 3h15) or connect from Seville.",
            lodging: "Seville: a 3–4BR apartment in Santa Cruz, Alfalfa or Triana — a roof terrace with a plunge pool is worth paying for in the heat — or an aparthotel. Granada: a carmen in the Albaicín (walled garden, Alhambra views; no car access, bags carried up stairs) or a Realejo apartment; hotel rooms with a lounge also fine. 7 = two apartments in the same building is common in Seville.",
            days7: [
              "D1 Land MAD, AVE to Seville (arrive ~3–4pm). Evening paseo: Plaza de España rowboats, María Luisa park playgrounds, early tapas.",
              "D2 Real Alcázar at opening (timed ticket; gardens, peacocks, hedge maze), Cathedral + Giralda — it's ramps all the way up, Penny walks it. Siesta. Early-evening flamenco at a small tablao (kids welcome at 6pm shows).",
              "D3 Triana: market breakfast, ceramics, river walk; afternoon Isla Mágica theme park or the Setas de Sevilla walkway at sunset.",
              "D4 Córdoba by AVE (45 min): Mezquita at opening, Jewish quarter and the patios (festival first half of May [verify]), Alcázar gardens, back by evening.",
              "D5 Train Seville → Granada (~2.5–3h). Check in. Mirador de San Nicolás at sunset, Albaicín wander, tetería.",
              "D6 Alhambra: Nasrid Palaces at the booked slot (tickets months ahead), Generalife gardens, Alcazaba towers. Afternoon Parque de las Ciencias (Granada's science museum — a big kid hit) or pool.",
              "D7 Sierra Nevada half-day: bus to Pradollano (~1h) for snow in May and sledging [verify what runs]; or Cathedral + Royal Chapel, Sacromonte caves, hammam for the adults in rotation.",
              "D8 AVE Granada → Madrid (3h15) and fly home same day [verify timing], or sleep in Madrid.",
            ],
            days10: [
              "4 nights Seville, 1 night Córdoba (patios at dusk without the day-trippers), 3 nights Granada, 1–2 nights Cádiz (train 1h40 from Seville: La Caleta beach, Torre Tavira camera obscura, fried fish).",
              "Extra Seville: Itálica Roman ruins (Game of Thrones), Carmona. Extra Granada: Alpujarras white villages (car), Nerja caves + beach (bus 2h), Ronda by train.",
              "Option: Cádiz instead of Granada for a sea version — less history, more beach, cooler.",
            ],
            anchorsKids: "Plaza de España rowboats, Alcázar peacocks and maze, Giralda ramps, Isla Mágica, Córdoba patios, Parque de las Ciencias, snow on the Sierra Nevada, churros con chocolate.",
            anchorsAdults: "Alhambra, Mezquita, Alcázar, flamenco, Albaicín at sunset, tapas culture, the AVE.",
            mayWeek: "Early May strongly preferred: Seville highs ~80°F early May, 90°F+ by late May. Córdoba patios festival runs roughly the first two weeks of May [verify]. Feria de Abril 2027 should fall mid/late April [verify] — if it slips into May, Seville lodging spikes. Alhambra tickets release ~3 months ahead and sell out [verify].",
            verify: [
              "IAD–MAD nonstop schedule May 2027",
              "AVE Madrid–Seville and Seville–Granada timetables",
              "Alhambra ticket release and Nasrid Palaces slots",
              "Córdoba patios festival 2027 dates",
              "Feria de Abril 2027 dates",
              "Sierra Nevada access in May",
            ],
          },
          status: "shortlisted",
          statusReason: "Shortlisted 2026-10-03 (top ten) with a detailed plan. Best history in Iberia, but no nonstop and the hottest May.",
        },
        {
          id: "barcelona-girona",
          name: "Barcelona + Girona / Costa Brava",
          bases: "Barcelona (5 nights) → Girona (3 nights)",
          type: "mixed",
          costTier: 3,
          flightHours: 8.5,
          direct: "yes",
          connectionCostsDay: "no",
          flightNote: "IAD–BCN nonstop (United) ~8.5h — has been near year-round, confirm May [verify].",
          train: "yes",
          trainHours: 0.7,
          trainNote: "Barcelona Sants → Girona AVE 38 min [verify]. Alternatives by rail: Valencia 3h, Madrid 2.5h, Figueres (Dalí) 55 min.",
          car: "none",
          carNote: "Not needed. A car is optional for Costa Brava coves (Calella de Palafrugell, Tossa) — otherwise buses from Girona.",
          rail: 5,
          kid3: 4,
          kid7: 5,
          scenery: 4,
          history: 3,
          beach: "yes",
          beachHow: "Barceloneta is walkable from the center; Costa Brava coves from Girona by bus or car. Sea ~65°F.",
          lodgingStyle: "Barcelona: licensed (HUT) apartment or aparthotel; Girona: old-town hotel or apartment.",
          lodging57: "Barcelona tightly regulates short-term rentals and has announced a phase-out of tourist apartments by 2028 — availability for a 4BR in 2027 is uncertain [verify]. 7 may mean an aparthotel or hotel family rooms.",
          weather: "Highs ~72°F, sea ~65°F, mostly dry.",
          notes: "Sagrada Família and Park Güell on timed tickets. Montjuïc cable car, Tibidabo (old-school amusement park with a funicular), Aquarium. Montserrat rack railway + funiculars is a great kid day. Girona is medieval and compact (Game of Thrones again) and Figueres has the Dalí museum. Because Girona is 38 min away, a single-base version with day trips is also valid.",
          openQuestions: [
            "Girona vs. Valencia vs. Madrid as the second base?",
            "Single base in Barcelona with day trips instead?",
          ],
          todos: [
            { text: "Check 2027 status of Barcelona tourist-apartment rules", done: false },
          ],
          verify: [
            "IAD–BCN nonstop schedule for May",
            "Barcelona short-term rental rules in 2027",
            "IAD–BCN nonstop schedule May 2027",
            "Barcelona tourist-apartment rules in 2027",
            "Montserrat boys' choir schedule",
            "Magic Fountain show schedule",
            "Girona–Costa Brava bus options",
            "Camp Nou tour status",
          ],
          detail: {
            arrival: "IAD–BCN nonstop, overnight, land ~morning [verify]. Aerobús or the R2 Nord train into the centre (~35 min). The jet-lag day is a beach-and-park day in Barcelona.",
            lodging: "Barcelona: a licensed (HUT) 3–4BR apartment in Eixample or Gràcia, or an aparthotel / hotel family suite — given the planned 2028 phase-out of tourist apartments, aparthotels are the safe bet for 7 [verify]. Girona: an old-town apartment or hotel; or swap Girona for a Costa Brava villa (Begur, Calella de Palafrugell — car needed) for the second half.",
            days7: [
              "D1 Land BCN. Barceloneta beach walk, Parc de la Ciutadella (rowboats, the mammoth, the cascade), early dinner.",
              "D2 Sagrada Família at opening (timed), Park Güell (timed), lunch in Gràcia; afternoon rest.",
              "D3 Montjuïc: cable car across the port from Barceloneta, castle, Poble Espanyol; Magic Fountain show in the evening if running [verify].",
              "D4 Montserrat: R5 train from Plaça Espanya + rack railway (Cremallera), funicular to Sant Joan, short ridge walk, boys' choir at 1pm (not Saturdays) [verify]. Back by evening.",
              "D5 AVE to Girona (38 min). City walls walk, cathedral steps (Game of Thrones), Jewish quarter, Onyar houses, gelato at Rocambolesc.",
              "D6 Costa Brava: bus or car to Calella de Palafrugell or Tossa de Mar — beach and a short stretch of the camí de ronda coastal path. Or Figueres Dalí museum by train (35 min).",
              "D7 Besalú (medieval bridge) + Banyoles lake (pedalos, swim) by bus/car, or a Girona rest day.",
              "D8 Train back to BCN airport (~1h30 with a change) and fly home.",
            ],
            days10: [
              "5 nights Barcelona (add CosmoCaixa science museum — superb for kids; Tibidabo amusement park + funicular; Picasso museum; Camp Nou tour [verify status]) + 4 nights Girona / Costa Brava.",
              "Extra Girona: Cadaqués + Cap de Creus by car, Empúries Greek and Roman ruins on the beach, the Dalí triangle (Figueres, Púbol, Portlligat).",
              "Option: 3 nights in a Costa Brava villa with a car instead of Girona town.",
            ],
            anchorsKids: "Barceloneta, Ciutadella rowboats, Sagrada Família towers, Montserrat rack railway, Magic Fountain, Tibidabo, CosmoCaixa, Costa Brava coves, Banyoles pedalos.",
            anchorsAdults: "Gaudí, Montserrat, Girona old town, Dalí, the camí de ronda, Catalan food and vermut.",
            mayWeek: "Any week; sea ~65°F — Simon will swim. Watch pockets on the metro. Sagrada Família and Park Güell timed tickets ~2 months out [verify]. Montserrat choir schedule [verify].",
            verify: [
              "IAD–BCN nonstop schedule May 2027",
              "Barcelona tourist-apartment rules in 2027",
              "Montserrat boys' choir schedule",
              "Magic Fountain show schedule",
              "Girona–Costa Brava bus options",
              "Camp Nou tour status",
            ],
          },
          status: "shortlisted",
          statusReason: "Shortlisted 2026-10-03 (top ten) with a detailed plan. Easy and fun, but the least 'novel' sketch in the bucket.",
        },
      ],
    },

    /* ================================================================
       2. UK
       ================================================================ */
    {
      id: "uk",
      name: "UK",
      type: "city",
      costTier: 4,
      railScore: 5,
      status: "researching",
      statusReason: "The rail spine is perfect and there's zero friction with kids; cost and weather are the knocks.",
      why: "No language barrier, dense kid-friendly museums (free), Harry Potter everywhere, and London–Edinburgh on LNER is exactly the rail spine we want. The West Highland Line adds world-class scenery without a car.",
      whyNot: "Second most expensive bucket after Switzerland; the least reliable weather; 'beach day' is a stretch; we may have done London before.",
      notes: "",
      openQuestions: [
        "Has Melissa done London/Edinburgh recently? If yes, does that push toward the Highlands version?",
        "UK ETA (electronic travel authorisation) is now required for US visitors — small fee per person, apply before flying [verify].",
      ],
      todos: [
        { text: "Check United IAD–EDI seasonal nonstop start date for 2027", done: false },
      ],
      subOptions: [
        {
          id: "london-edinburgh",
          name: "London + Edinburgh",
          bases: "London (4–5 nights) → Edinburgh (3–4 nights)",
          type: "city",
          costTier: 4,
          flightHours: 7,
          direct: "yes",
          connectionCostsDay: "no",
          flightNote: "IAD–LHR nonstop, many daily (United, BA, Virgin) ~7h [verify]. Fly home from Edinburgh if United's seasonal IAD–EDI nonstop runs by May [verify].",
          train: "yes",
          trainHours: 4.5,
          trainNote: "LNER King's Cross → Edinburgh Waverley ~4h20, 2 per hour [verify]. Advance fares open ~12 weeks out; first class with a table is worth it for 7 people.",
          car: "none",
          carNote: "Not needed anywhere. Day trips from Edinburgh by train: Stirling (50 min), North Berwick seaside (30 min), the Forth Bridge.",
          rail: 5,
          kid3: 4,
          kid7: 5,
          scenery: 3,
          history: 4,
          beach: "limited",
          beachHow: "Portobello Beach, 20 min by bus from Edinburgh, or North Berwick by train. Sandy, cold, ice cream — a beach day in spirit.",
          lodgingStyle: "Flats in London (Bloomsbury / Marylebone / South Ken) and New Town Edinburgh; or hotels with family rooms.",
          lodging57: "London 4BR flats are expensive and rare; 7 = two flats, an aparthotel (Citadines, Native), or Premier Inn family rooms. Edinburgh New Town 4BR flats are more findable.",
          weather: "London highs ~64°F, Edinburgh ~58°F, showers any day. Light until 9:30pm by late May.",
          notes: "London: Natural History Museum, Science Museum, Tower, Thames Clipper boat, Diana playground, Platform 9¾; Warner Bros Studio Tour (Watford) must be booked months ahead. Edinburgh: Castle (one o'clock gun), Arthur's Seat is a doable hike for Simon and Melissa, Camera Obscura, Royal Yacht Britannia, Victoria Street. Caledonian Sleeper is an alternative to the day train — family cabins.",
          openQuestions: [
            "Open-jaw LHR in / EDI out?",
            "Day train vs. Caledonian Sleeper?",
          ],
          todos: [
            { text: "Check WB Studio Tour ticket release timing", done: false },
            { text: "Check LNER advance fare release for the chosen week", done: false },
          ],
          verify: [
            "IAD–EDI seasonal nonstop season start",
            "LNER timetable and advance-fare window",
            "WB Studio Tour ticket availability",
            "UK ETA requirement and fee",
            "IAD–EDI seasonal nonstop 2027 start",
            "LNER advance fare release",
            "WB Studio Tour ticket release",
            "UK ETA fee and process",
            "UK bank holiday dates 2027",
            "Bass Rock boat season",
          ],
          detail: {
            arrival: "IAD–LHR nonstop, overnight [verify]. Elizabeth line into town (~45 min). Fly home from Edinburgh on United's seasonal nonstop if it is running by May [verify], otherwise a short EDI–LHR hop.",
            lodging: "London: a 3–4BR flat in Bloomsbury, Marylebone or Pimlico, or an aparthotel with a living room (Citadines, Native, Cheval). Premier Inn family rooms are the cheap fallback but give the adults no shared space unless rooms adjoin. Edinburgh: New Town or Stockbridge 3–4BR flats are plentiful and good value.",
            days7: [
              "D1 Land LHR. Hyde Park: Diana Memorial Playground, Serpentine pedalos; early night.",
              "D2 Natural History Museum at opening + Science Museum Wonderlab; Thames Clipper to the Tower of London (Crown Jewels, Yeoman Warder tour).",
              "D3 Warner Bros Studio Tour (Watford Junction; book months ahead) — or British Museum + Platform 9¾ + Covent Garden performers if tickets are gone.",
              "D4 Greenwich by boat: Cutty Sark, Royal Observatory meridian line, the park; or Kew Gardens treetop walk. Pack.",
              "D5 LNER King's Cross → Edinburgh Waverley (4h20, first-class table). Royal Mile, Camera Obscura, Victoria Street, Greyfriars Bobby.",
              "D6 Edinburgh Castle at opening (one o'clock gun); Grassmarket lunch; Arthur's Seat via the Salisbury Crags path; dinner in Stockbridge.",
              "D7 North Berwick by train (30 min): beach, Scottish Seabird Centre, boat to the Bass Rock gannets — or Royal Yacht Britannia + Dynamic Earth + Portobello beach.",
              "D8 Fly home from EDI (nonstop if running) [verify].",
            ],
            days10: [
              "5 nights London + 5 nights Edinburgh.",
              "Extra London: Kew, Hampton Court maze, Windsor, a West End matinee (Lion King / Matilda), Borough Market, Changing of the Guard.",
              "Extra Edinburgh: Stirling Castle + Wallace Monument by train (50 min); Glasgow day (Kelvingrove, Riverside transport museum); Forth Bridge boat from South Queensferry; Fife coast (Anstruther fish and chips, St Andrews); Rosslyn Chapel.",
            ],
            anchorsKids: "Diana playground, dinosaurs, Wonderlab, Tower ravens, Platform 9¾ and the Studio Tour, Thames boats, the castle gun, Arthur's Seat scramble, Bass Rock boat, Portobello ice cream.",
            anchorsAdults: "Tower, Greenwich, a West End show, Edinburgh old and new towns, Stockbridge, the Fife coast.",
            mayWeek: "Any week. UK bank holidays Mon May 3 and Mon May 31, 2027 crowd the museums [verify]. Light until 10pm in Edinburgh by late May. UK ETA required for every traveller [verify]. Studio Tour tickets and LNER advance fares open ~3 months ahead [verify].",
            verify: [
              "IAD–EDI seasonal nonstop 2027 start",
              "LNER advance fare release",
              "WB Studio Tour ticket release",
              "UK ETA fee and process",
              "UK bank holiday dates 2027",
              "Bass Rock boat season",
            ],
          },
          status: "shortlisted",
          statusReason: "Shortlisted 2026-10-03 (top ten) with a detailed plan. Cleanest pure-rail two-base trip on the board.",
        },
        {
          id: "london-highlands-rail",
          name: "London + Edinburgh + Highlands by rail",
          bases: "London (3 nights) → Edinburgh (2–3 nights) → Fort William / Glencoe area (3 nights)",
          type: "mixed",
          costTier: 4,
          flightHours: 7,
          direct: "yes",
          connectionCostsDay: "no",
          flightNote: "IAD–LHR nonstop ~7h [verify]. Return from Edinburgh or Glasgow (Glasgow has no IAD nonstop — connect) [verify].",
          train: "yes",
          trainHours: 4.5,
          trainNote: "London–Edinburgh 4h20; Edinburgh–Glasgow 50 min; Glasgow–Fort William on the West Highland Line 3h45 (Rannoch Moor); Fort William–Mallaig on the Jacobite steam train (~2h) or ScotRail (1h20) [verify].",
          car: "none",
          carNote: "Not needed. Citylink buses 914/915/916 run through Glencoe. Skye reachable as a day by ferry Mallaig–Armadale.",
          rail: 5,
          kid3: 4,
          kid7: 5,
          scenery: 5,
          history: 3,
          beach: "limited",
          beachHow: "Silver Sands of Morar / Camusdarach near Mallaig — stunning white sand, very cold water.",
          lodgingStyle: "London flat, Edinburgh flat, then a Highland cottage or hotel. Fort William town is utilitarian — consider Glencoe/Ballachulish, Arisaig or Mallaig.",
          lodging57: "Lochaber self-catering cottages sleeping 6–8 are common; 7 fine. London remains the hard part (see London + Edinburgh).",
          weather: "Highlands highs ~55°F, rain possible any day, long light. Midges start late May (mild), bad from June.",
          notes: "This is really three bases — fits 10 days, tight at 7. The Jacobite over the Glenfinnan Viaduct is the 'Hogwarts Express'; it typically runs from ~April with a second daily departure from mid-May and sells out months ahead [verify]. Nevis Range gondola (check spring maintenance), Loch Shiel boat, Glencoe visitor centre. Steall Falls walk in Glen Nevis is a good accessible hike.",
          openQuestions: [
            "Does this need the full 10 days?",
            "Cut London to 2 nights or skip it (fly into EDI if the nonstop runs)?",
          ],
          todos: [
            { text: "Check Jacobite 2027 operating dates and booking opening", done: false },
            { text: "Check Nevis Range spring maintenance closure", done: false },
          ],
          verify: [
            "Jacobite steam train 2027 schedule",
            "West Highland Line timetable",
            "Nevis Range gondola spring closure dates",
            "IAD–EDI seasonal nonstop 2027 start",
            "Jacobite 2027 dates and booking opening",
            "LNER advance fares release",
            "WB Studio Tour ticket release",
            "Nevis Range spring maintenance",
            "UK ETA fee and process",
          ],
          detail: {
            arrival: "IAD–LHR nonstop, overnight [verify]. Elizabeth line or Heathrow Express into town. Three bases means this is a 9–10 night trip under the 3-night rule; a 7-night version is really London + Edinburgh only.",
            lodging: "Highlands: Lochaber self-catering houses for 6–8 are everywhere and May is quiet. London: a 3–4BR flat in Bloomsbury/Marylebone or an aparthotel (Citadines, Native) with a living room; a house in Hampstead or Richmond at a price. Edinburgh: New Town 3–4BR flats are findable.",
            days7: [
              "Tight but possible with 2 nights in London: D1–2 London (arrival day + one full museum day), D3 LNER to Edinburgh, D4 Edinburgh castle + Arthur's Seat, D5 West Highland Line to Fort William, D6 Jacobite to Mallaig, D7 Glencoe, D8 fly home from EDI/GLA via LHR. You lose London depth; the trade is worth it only if London is a repeat for the group.",
            ],
            days10: [
              "D1 Land LHR. Hyde Park / Diana playground, Thames Clipper boat to Greenwich or Tower, early night.",
              "D2 Natural History Museum (dinosaurs, Simon) + Science Museum Wonderlab, South Ken lunch. Afternoon Tower of London (Crown Jewels, ravens).",
              "D3 Warner Bros Studio Tour (Watford Junction, 20 min from Euston; booked months ahead) — or Platform 9¾ + British Museum if tickets are gone. Evening Covent Garden street performers.",
              "D4 LNER King's Cross → Edinburgh Waverley (4h20, book a table in first). Afternoon Royal Mile, Camera Obscura, Victoria Street.",
              "D5 Edinburgh Castle at opening (one o'clock gun), lunch in Grassmarket, afternoon Arthur's Seat (Simon will summit; Penny rides shoulders to the Salisbury Crags path).",
              "D6 North Berwick by train (30 min): beach, Scottish Seabird Centre, boat to Bass Rock gannets. Or Royal Yacht Britannia + Portobello beach.",
              "D7 Edinburgh → Glasgow (50 min) → Fort William on the West Highland Line (3h45: Loch Lomond, Rannoch Moor, Corrour). Check into a house near Glencoe/Ballachulish or Arisaig.",
              "D8 Jacobite steam train Fort William → Mallaig over Glenfinnan Viaduct (book months ahead; typically running from April, two departures from mid-May [verify]). Mallaig fish and chips, Silver Sands of Morar beach on the way back (ScotRail return).",
              "D9 Glencoe: visitor centre, Glencoe Lochan walk, bus 915 along the glen. Or Nevis Range gondola + Steall Falls walk in Glen Nevis (easy, dramatic).",
              "D10 Train to Glasgow or Edinburgh and fly home from EDI if United's seasonal nonstop runs, else back to LHR via a domestic hop [verify].",
            ],
            anchorsKids: "Diana playground, dinosaurs, Wonderlab, Platform 9¾, castle gun, Arthur's Seat, Bass Rock boat, the Hogwarts Express, beach at Morar, Glencoe cows.",
            anchorsAdults: "Tower, West Highland Line, Glenfinnan, Glencoe, Edinburgh old town.",
            mayWeek: "Any week. Jacobite second daily departure from mid-May helps availability [verify]. Midges start late May but are mild. Light until 10pm in the Highlands by late May. UK ETA required for all US travellers [verify].",
            verify: [
              "IAD–EDI seasonal nonstop 2027 start",
              "Jacobite 2027 dates and booking opening",
              "LNER advance fares release",
              "WB Studio Tour ticket release",
              "Nevis Range spring maintenance",
              "UK ETA fee and process",
            ],
          },
          status: "shortlisted",
          statusReason: "Shortlisted 2026-10-03 with a detailed plan (see Plan below). Best scenery in the UK bucket, all-rail, but three bases.",
        },
        {
          id: "london-scotland-car",
          name: "London + Scotland with a hire car",
          bases: "London (3–4 nights) → Edinburgh (2 nights) → Highlands / Skye with a car (4 nights)",
          type: "mixed",
          costTier: 4,
          flightHours: 7,
          direct: "yes",
          connectionCostsDay: "no",
          flightNote: "IAD–LHR nonstop ~7h [verify]; return from EDI (seasonal nonstop) or Inverness via LHR [verify].",
          train: "yes",
          trainHours: 4.5,
          trainNote: "London–Edinburgh by LNER 4h20 [verify]. Alternatively train on to Inverness (3.5h from Edinburgh) and pick up the car there to cut driving.",
          car: "needed",
          carNote: "Needed for Glencoe + Skye + Cairngorms. Drive on the left; single-track roads with passing places. 7 people = 9-seat van or two cars [verify availability].",
          rail: 3,
          kid3: 4,
          kid7: 4,
          scenery: 5,
          history: 3,
          beach: "limited",
          beachHow: "Nairn beach near Inverness (sandy), Coral Beach on Skye. Cold.",
          lodgingStyle: "Flats in London/Edinburgh, then a Highland self-catering house.",
          lodging57: "Highland big houses for 7 are plentiful and good value; London is the constraint as always.",
          weather: "Highlands ~55°F, changeable; Skye wetter than the east.",
          notes: "Unlocks Skye (Fairy Pools, Quiraing, Old Man of Storr — crowds now significant even in May), Glencoe, Highland Wildlife Park (polar bears, drive-through reserve), Cairngorm funicular, Urquhart Castle / Loch Ness, Culloden, Eilean Donan. Long driving days are the cost; it is a different trip from the rail versions.",
          openQuestions: [
            "Is the car worth it vs. the all-rail Highlands version?",
            "Inverness vs. Fort William as the Highland pick-up point?",
          ],
          todos: [
            { text: "Price 9-seat van hire from Edinburgh/Inverness for a May week", done: false },
          ],
          verify: [
            "9-seat van availability and price",
            "Skye ferry/bridge logistics",
            "Highland Wildlife Park opening hours",
          ],
          status: "idea",
          statusReason: "Scenery payoff is big but it breaks the rail rule.",
        },
      ],
    },

    /* ================================================================
       3. ALPS
       ================================================================ */
    {
      id: "alps",
      name: "Alps",
      type: "mountains",
      costTier: 4,
      railScore: 4,
      status: "researching",
      statusReason: "Best fit to 'scenery and towns'; the May shoulder season is the thing to understand before committing.",
      why: "Scenery and storybook towns are exactly the brief; Switzerland and Bavaria are genuinely car-free trips; cog railways, cable cars, lake steamers and cows are catnip for Penny and Simon.",
      whyNot: "MAY IS SHOULDER SEASON. Snow lingers above ~1,800 m; many high lifts, passes and mountain huts open in June, so the famous high hikes are mostly off. Rain is likelier than in Iberia. Switzerland is the priciest option on the board.",
      notes: "Shoulder-season rule of thumb: year-round 'flagship' lifts (Jungfraujoch, Schilthorn, Zugspitze, Aiguille du Midi, Titlis, Rigi) run in May with possible short maintenance closures; mid-mountain gondolas (Grindelwald First, Männlichen, Brévent, Dolomites lifts) often reopen mid/late May or June; valley-floor and lakeside walks are fine everywhere. Each sketch below lists what is realistically open — all dates need verifying for 2027.",
      openQuestions: [
        "How much do we care about actual hiking vs. riding lifts and walking in towns? May favors the latter.",
        "Which week? Late May opens materially more than early May across all five sketches.",
      ],
      todos: [
        { text: "Build a single 'what opens when' table across the five Alps sketches once the week is known", done: false },
      ],
      subOptions: [
        {
          id: "swiss-lucerne-bo",
          name: "Switzerland: Lucerne + Berner Oberland",
          bases: "Lucerne (3 nights) → Lauterbrunnen / Wengen / Grindelwald (4–5 nights); Bern as a stop between",
          type: "mountains",
          costTier: 5,
          flightHours: 8.5,
          direct: "yes",
          connectionCostsDay: "no",
          flightNote: "IAD–ZRH nonstop (United; Swiss has also flown it) ~8h20 [verify]. Zurich airport has its own rail station.",
          train: "yes",
          trainHours: 2,
          trainNote: "Zurich–Lucerne 45 min; Luzern–Interlaken Express 1h50 over the Brünig Pass (panorama car); Interlaken–Lauterbrunnen 20 min; Bern is 1h from either for a half-day old-town stop [verify].",
          car: "none",
          carNote: "Zero car. Lauterbrunnen valley above the floor is car-free (Wengen, Mürren). Swiss Travel Pass or Berner Oberland Pass + Swiss Family Card (kids under 16 free with a parent) [verify pass seasons].",
          rail: 5,
          kid3: 5,
          kid7: 5,
          scenery: 5,
          history: 3,
          beach: "no",
          beachHow: "Lakes are cold in May. Lido Luzern or Strandbad Thun for a paddle on a warm day — not a beach day.",
          lodgingStyle: "Apartment or hotel in Lucerne; chalet apartment in Wengen / Mürren / Lauterbrunnen / Grindelwald.",
          lodging57: "5 fits a standard 2–3BR chalet apartment. 7 = a larger chalet, easiest in Grindelwald or Wilderswil; Wengen/Mürren have fewer big units. Lucerne 7 = two hotel rooms + a triple, or an aparthotel.",
          weather: "Lucerne / Interlaken highs ~65°F, rain about one day in three, Föhn days are warm and clear. Above 2,000 m it is winter: Jungfraujoch ~20°F.",
          notes: "OPEN IN MAY (verify all for 2027): Jungfraujoch (year-round; 3,454 m — fine for a short visit, keep Penny hydrated), Schilthorn / Piz Gloria + Birg Thrill Walk (year-round), Rigi and Titlis (year-round), Pilatus gondola from Kriens (year-round; the cogwheel from Alpnachstad usually opens mid-May), Harder Kulm funicular (from ~April), Trümmelbach Falls (from early April), Lake Lucerne paddle steamers, Swiss Transport Museum, Ballenberg open-air museum (from mid-April), Bern bear park and old town. USUALLY NOT YET: Grindelwald First gondola (spring maintenance ~mid-April to mid/late May), Männlichen cable cars (reopen late May), Schynige Platte (June), high trails like Männlichen–Kleine Scheidegg and First–Bachalpsee (snow into June). ACCESSIBLE WALKS that are fine in May: Lauterbrunnen → Stechelberg valley floor, Mürren → Gimmelwald, Wengen village paths, Lucerne lakeside.",
          openQuestions: [
            "Wengen (car-free, sunny shelf) vs. Lauterbrunnen (valley floor, train hub) vs. Grindelwald (bigger, more lodging for 7)?",
            "Jungfraujoch for everyone, or adults only with Penny doing Kleine Scheidegg?",
          ],
          todos: [
            { text: "Pull 2027 opening dates: Männlichen, First, Pilatus cogwheel, Schynige Platte", done: false },
            { text: "Compare Swiss Travel Pass vs. Berner Oberland Pass for our dates", done: false },
          ],
          verify: [
            "IAD–ZRH nonstop schedule",
            "Lift and cog-railway opening dates for May 2027 (Männlichen, First, Pilatus cogwheel, Schynige Platte, Harder Kulm)",
            "Berner Oberland Pass season start",
            "Luzern–Interlaken Express timetable",
            "IAD–ZRH nonstop schedule May 2027",
            "Männlichen, First, Pilatus cogwheel, Schynige Platte 2027 opening dates",
            "Berner Oberland Pass season start and coverage",
            "Chalet inventory for 7 in Grindelwald / Wilderswil / Wengen",
            "Jungfraujoch altitude guidance for Penny",
          ],
          detail: {
            arrival: "IAD–ZRH nonstop, overnight, land ~morning [verify]. Train from the airport station straight to Lucerne (~1h, one change at Zurich HB or direct). First day is a lakeside walk and an early night.",
            lodging: "Berner Oberland: Grindelwald and Wilderswil have the most 4–5BR chalets; Wengen and Mürren have a few (car-free, bags from the train). Lucerne: aparthotel or a 2–3BR apartment in the old town; hotel rooms work if there's a lounge. Worth considering 2 nights Lucerne + 6–7 nights in one chalet, day-tripping Lucerne and Bern by train, since the chalet is where the evenings are best.",
            days7: [
              "D1 Land ZRH, train to Lucerne. Chapel Bridge, Lion Monument, lakeside promenade, early dinner.",
              "D2 Mount Pilatus: gondola from Kriens up, cogwheel down to Alpnachstad (the cogwheel usually opens mid-May — if closed, gondola both ways), paddle steamer back to Lucerne.",
              "D3 Swiss Transport Museum (half a day easily for both kids), afternoon Rigi by boat + cogwheel from Vitznau, or a rest afternoon.",
              "D4 Luzern–Interlaken Express over the Brünig Pass (1h50, sit on the right for the lakes), change at Interlaken Ost for Lauterbrunnen/Wengen/Grindelwald. Check in. Trümmelbach Falls in the afternoon (10 glacier waterfalls inside the mountain, lift inside).",
              "D5 Jungfraujoch: train via Kleine Scheidegg to the Top of Europe. Ice Palace, Sphinx terrace, snow play. Short visit for Penny (altitude), then Kleine Scheidegg for lunch and the Männlichen walk only if open [verify].",
              "D6 Mürren and Schilthorn: cable car Stechelberg → Mürren, walk Mürren → Gimmelwald (easy, downhill, 45 min, cows), Schilthorn/Piz Gloria for the 360° and the Birg Thrill Walk.",
              "D7 Easy day: Lauterbrunnen valley floor walk to Stechelberg (flat, 72 waterfalls), Interlaken Harder Kulm funicular at golden hour, or a Bern half-day (bear park, old-town arcades, Zytglogge).",
              "D8 Train Interlaken → ZRH (~2h20) and fly home.",
            ],
            days10: [
              "4 nights Lucerne (add Titlis Rotair rotating cable car from Engelberg, or Bern as a day) + 5–6 nights Oberland.",
              "Extra Oberland days: Grindelwald First (if reopened — usually mid/late May [verify]) for the cliff walk and Bachalpsee if snow-free; Ballenberg open-air museum (farmhouses, animals, bread baking — a full kid day); Lake Thun boat to Spiez or Oberhofen castle; Blausee.",
              "Option: Bern as a one-night stop between Lucerne and the Oberland instead of a day trip.",
            ],
            anchorsKids: "Pilatus cogwheel, paddle steamers, Transport Museum, Trümmelbach, Jungfraujoch snow, cows and cowbells on the Mürren–Gimmelwald walk, Ballenberg, Harder Kulm.",
            anchorsAdults: "Jungfraujoch, Schilthorn, Brünig Pass train, Lauterbrunnen valley, Bern old town, Rigi.",
            mayWeek: "Late May opens materially more: Männlichen and First usually reopen in the second half of May, Pilatus cogwheel mid-May [verify]. Early May = flagship lifts only, valley walks, lake boats. Swiss Family Card makes kids under 16 free with a paying parent on most of this [verify].",
            verify: [
              "IAD–ZRH nonstop schedule May 2027",
              "Männlichen, First, Pilatus cogwheel, Schynige Platte 2027 opening dates",
              "Berner Oberland Pass season start and coverage",
              "Chalet inventory for 7 in Grindelwald / Wilderswil / Wengen",
              "Jungfraujoch altitude guidance for Penny",
            ],
          },
          status: "shortlisted",
          statusReason: "Shortlisted 2026-10-03 with a detailed plan (see Plan below). Best fit to the brief; cost is the only knock, and cost is a tiebreaker.",
        },
        {
          id: "austria-salzburg",
          name: "Austria: Salzburg + Salzkammergut",
          bases: "Salzburg (3–4 nights) → Wolfgangsee / Bad Goisern / Obertraun (4 nights) for Hallstatt and the lakes",
          type: "mixed",
          costTier: 3,
          flightHours: 8.5,
          direct: "yes",
          connectionCostsDay: "no",
          flightNote: "No nonstop to Salzburg. IAD–MUC nonstop ~8.5h + 1.5h train [verify]; or IAD–VIE nonstop (Austrian) ~9h + 2.5h Railjet [verify].",
          train: "yes",
          trainHours: 2.5,
          trainNote: "Munich–Salzburg Railjet 1h30. Salzburg–Hallstatt ~2.5h by train via Attnang-Puchheim, finishing with the ferry across the lake. Salzburg–St. Gilgen Postbus 150 ~50 min [verify].",
          car: "optional",
          carNote: "Train + Postbus + lake boats cover Hallstatt, St. Wolfgang, Bad Ischl. A car speeds up lake-hopping and unlocks Gosausee, Dachstein and Berchtesgaden. 7 = van.",
          rail: 4,
          kid3: 4,
          kid7: 5,
          scenery: 5,
          history: 3,
          beach: "limited",
          beachHow: "Lake 'Strandbads' at Wolfgangsee / Mondsee open late May, water ~60°F — paddle and pebbles, not a beach day.",
          lodgingStyle: "Salzburg apartment or hotel; lakeside Ferienwohnung or Gasthof in the Salzkammergut. Do not sleep in Hallstatt itself — tiny, mobbed by day; visit early from Obertraun or Bad Goisern.",
          lodging57: "7 is easy in a lakeside Ferienwohnung or two units at a Gasthof. Salzburg 4BR apartments exist in the Neustadt.",
          weather: "Highs ~65°F. Salzburg's 'Schnürlregen' is real — expect some all-day rain. Snow above ~1,800 m.",
          notes: "OPEN IN MAY (verify 2027): Hallstatt salt mine with the wooden miners' slides (from late March; minimum age ~4 — Penny may be excluded [verify]), Dachstein ice cave and Mammoth cave (open ~May 1), Schafberg steam cog railway from St. Wolfgang (opens early/mid May), Untersberg cable car (year-round except maintenance), Hohensalzburg fortress funicular, Hellbrunn trick fountains (from late March — Simon's favorite 20 minutes of the trip), Wolfgangsee boats (from late April), Sound of Music tour (year-round). CAR-ONLY: Großglockner High Alpine Road (opens early May weather permitting), Eagle's Nest road (mid-May). The Obersalzberg / Eagle's Nest is the WWII question in this sketch too.",
          openQuestions: [
            "Fly into Munich or Vienna? Vienna adds a city, Munich is shorter.",
            "Lake base: St. Wolfgang (Schafberg, boats) vs. Obertraun (Hallstatt, Dachstein)?",
          ],
          todos: [
            { text: "Confirm Hallstatt salt mine minimum age", done: false },
            { text: "Pull Schafbergbahn and Dachstein caves 2027 opening dates", done: false },
          ],
          verify: [
            "IAD–VIE nonstop schedule (Austrian)",
            "Hallstatt salt mine minimum age",
            "Schafbergbahn, Dachstein caves, Eagle's Nest road, Großglockner opening dates",
            "Salzburg–Hallstatt train + ferry connection",
            "IAD–MUC and IAD–VIE nonstop schedules",
            "Schafbergbahn, Dachstein caves, Eagle's Nest road, Eisriesenwelt 2027 opening dates",
            "Postbus 150 and Salzburg–Hallstatt timetables",
            "Munich–Salzburg Railjet times",
            "Pfingsten 2027 crowds",
          ],
          detail: {
            arrival: "IAD–MUC nonstop, overnight, land ~morning [verify]. S-Bahn to Munich Hbf (45 min), Railjet to Salzburg (1h30) — in Salzburg by early afternoon the same day. Alternative: IAD–VIE nonstop (Austrian) + Railjet 2h30 [verify].",
            lodging: "Salzburg: a 3–4BR apartment in the Neustadt / Andräviertel or an aparthotel; the Altstadt is cramped. Salzkammergut: a lakeside Ferienwohnung in St. Wolfgang or St. Gilgen (Wolfgangsee side) or Obertraun / Bad Goisern (Hallstatt side); family farm apartments with a trampoline in the yard are the local speciality and 7 is easy.",
            days7: [
              "D1 Land MUC, train to Salzburg. Mirabell gardens (the Do-Re-Mi steps), Getreidegasse, early dinner in a Gastgarten.",
              "D2 Hohensalzburg fortress by funicular at opening (marionette museum, towers); afternoon Hellbrunn trick fountains + the palace-park playground + Salzburg Zoo next door.",
              "D3 Königssee day (bus 840, 50 min): electric boats to St. Bartholomä, the echo trumpet, a lakeside walk. Or the Untersberg cable car (snow on top in May). Obersalzberg / Eagle's Nest for the adults in rotation — road opens ~mid-May [verify].",
              "D4 Postbus 150 Salzburg → St. Gilgen (50 min), boat across to St. Wolfgang; check into the lake house. Zwölferhorn cable car or pedalos.",
              "D5 Schafberg steam cog railway from St. Wolfgang (opens early/mid May [verify]) for the 360° of lakes; afternoon boat or lake bath.",
              "D6 Hallstatt early (train + ferry, or 1h drive): salt mine with the wooden slides (min age ~4 [verify] — one adult takes Penny to the Skywalk), then Dachstein ice cave from Obertraun (from ~May 1 [verify]) or the flat Gosausee lake walk.",
              "D7 Bad Ischl (Kaiservilla, Zauner pastry) + Katrin cable car; or Mondsee (Sound of Music church) + a Fuschlsee swim. Pack.",
              "D8 Bus/train to Salzburg (1h), Railjet to Munich (1h30), S-Bahn to MUC — fly home same day [verify] or sleep near the airport.",
            ],
            days10: [
              "4 nights Salzburg (add Werfen: Eisriesenwelt ice cave + falconry at Hohenwerfen castle, both from ~May 1 [verify]; a Munich day on arrival) + 5–6 nights on the lakes.",
              "Extra lakes: Attersee, Gmunden (Traunsee ship + Grünberg cable car), the Wolfgangsee bike circuit, Postalm plateau, Dachstein Krippenstein '5 Fingers' viewpoint if the lifts are running [verify].",
              "Car option: Großglockner High Alpine Road as a day (opens early May weather permitting [verify]).",
            ],
            anchorsKids: "Hellbrunn trick fountains, fortress funicular, Mirabell steps, lake boats and pedalos, Schafberg steam train, salt-mine slides (Simon), ice cave, Königssee electric boats, cows with bells, the farm trampoline.",
            anchorsAdults: "Hohensalzburg, DomQuartier, Hallstatt at dawn, Gosausee, Schafberg panorama, Gasthaus food, Bad Ischl's imperial history.",
            mayWeek: "Mid or late May is better: Schafbergbahn and the Eagle's Nest road open ~mid-May, Dachstein caves and Eisriesenwelt from May 1 [verify]. Budget two wet days (Schnürlregen) with indoor fallbacks: Haus der Natur, salt mine, ice cave. Whit Monday is May 17, 2027 — Hallstatt will be mobbed that weekend [verify].",
            verify: [
              "IAD–MUC and IAD–VIE nonstop schedules",
              "Schafbergbahn, Dachstein caves, Eagle's Nest road, Eisriesenwelt 2027 opening dates",
              "Hallstatt salt mine minimum age",
              "Postbus 150 and Salzburg–Hallstatt timetables",
              "Munich–Salzburg Railjet times",
              "Pfingsten 2027 crowds",
            ],
          },
          status: "shortlisted",
          statusReason: "Shortlisted 2026-10-03 (top ten) with a detailed plan. Great scenery-to-cost ratio; rail is good but not perfect.",
        },
        {
          id: "bavaria-munich-garmisch",
          name: "Bavaria: Munich + Garmisch-Partenkirchen (or Füssen)",
          bases: "Munich (3–4 nights) → Garmisch-Partenkirchen (4 nights); Füssen / Neuschwanstein as a day or a swap",
          type: "mixed",
          costTier: 3,
          flightHours: 8.5,
          direct: "yes",
          connectionCostsDay: "no",
          flightNote: "IAD–MUC nonstop (United, Lufthansa) ~8.5h [verify]. S-Bahn from the airport.",
          train: "yes",
          trainHours: 1.3,
          trainNote: "Munich–Garmisch regional 1h20, hourly. Munich–Füssen ~2h with one change. Garmisch–Füssen bus ~2h via Oberammergau. Garmisch–Innsbruck 1h20 for a second-country day [verify].",
          car: "none",
          carNote: "Doable without a car on regional trains and buses (the Deutschlandticket covers all of them — price and visitor availability for 2027 [verify]). A car is optional for Linderhof + Neuschwanstein + Eibsee in one day.",
          rail: 5,
          kid3: 5,
          kid7: 5,
          scenery: 5,
          history: 4,
          beach: "no",
          beachHow: "Eibsee and Starnberger See swim spots are cold in May. No beach day.",
          lodgingStyle: "Munich apartment or aparthotel; Garmisch Ferienwohnung (abundant).",
          lodging57: "Munich 4BR apartments are scarce and pricey — 7 = aparthotel or two units. Garmisch and Schwangau have plenty of large Ferienwohnungen; 7 is easy.",
          weather: "Munich ~66°F, Garmisch ~62°F, afternoon thunderstorms possible, snow line ~1,800 m.",
          notes: "OPEN IN MAY (verify 2027): Zugspitze cogwheel + Eibsee cable car (year-round, short spring maintenance windows), Alpspitzbahn + AlpspiX platform (usually open), Partnach Gorge (year-round, kids love it), Neuschwanstein (year-round, timed tickets released online weeks/months ahead), Linderhof, Eibsee boats, Mittenwald + Karwendelbahn, Königssee boats near Berchtesgaden (year-round). USUALLY NOT YET: Wank cable car (often reopens in May — check), high Wetterstein trails. Munich: Deutsches Museum Kids' Kingdom, Hellabrunn zoo, English Garden surfers, Residenz, Nymphenburg. Dachau memorial is 30 min by S-Bahn — the split-the-group question applies here too. No Oberammergau Passion Play in 2027 (next is 2030).",
          openQuestions: [
            "Garmisch (Zugspitze, gorge, Innsbruck day) vs. Füssen (Neuschwanstein, Forggensee) as the mountain base?",
            "Dachau: adults split, or skip?",
          ],
          todos: [
            { text: "Check Deutschlandticket availability/price for visitors in 2027", done: false },
            { text: "Check Zugspitze and Alpspitze spring maintenance dates", done: false },
            { text: "Check Neuschwanstein ticket release window", done: false },
          ],
          verify: [
            "IAD–MUC nonstop schedule",
            "Deutschlandticket 2027 price and tourist availability",
            "Zugspitze / Alpspitzbahn / Wankbahn spring maintenance",
            "Neuschwanstein ticket release timing",
            "IAD–MUC nonstop days of week for May 2027",
            "Zugspitze / Eibsee cable car spring maintenance dates",
            "Neuschwanstein ticket release window and group booking rules",
            "Deutschlandticket 2027 price and tourist eligibility",
            "Garmisch Ferienhaus inventory for 7",
          ],
          detail: {
            arrival: "IAD–MUC nonstop, overnight, land ~morning [verify]. S-Bahn S8 to Munich Hbf (~45 min). Start in Munich so the jet-lag day is a city day with early bed; move to the mountains once everyone is on local time.",
            lodging: "Garmisch: 4–5BR Ferienhäuser with gardens and mountain views are common in Garmisch, Grainau and Farchant, and May is low season — easy evening space. Munich: aparthotel suites with living rooms (Adina, Living Hotel) or two adjacent apartments in Lehel/Glockenbach; both give the adults a shared room after bedtime.",
            days7: [
              "D1 Land MUC, S-Bahn to Munich. Walk Marienplatz at the 11am/noon Glockenspiel, Viktualienmarkt lunch, nap, early dinner at a beer garden (kids welcome, playgrounds attached).",
              "D2 Munich: Deutsches Museum (Kids' Kingdom for Penny, mining/aviation for Simon), afternoon Englischer Garten — Eisbach surfers, Chinese Tower beer garden.",
              "D3 Munich: Hellabrunn Zoo morning (U-Bahn, large, stroller-easy), afternoon Nymphenburg palace gardens or Olympiapark tower. Evening pack.",
              "D4 Regional train Munich → Garmisch (1h20). Check into the house. Afternoon Partnach Gorge (30 min walk from the Olympic ski stadium, wet and loud, both kids will love it).",
              "D5 Zugspitze: cogwheel from Garmisch to Eibsee, Eibsee cable car to the summit, cog train back down through the mountain. Lunch on top (winter up there — hats). Afternoon Eibsee lakeshore walk.",
              "D6 Neuschwanstein + Linderhof day. Train/bus via Oberammergau, or hire a car for this one day (easiest with 5+). Timed tickets booked in advance. Hohenschwangau is the better castle for Simon's attention span.",
              "D7 Easy day: Alpspitzbahn to the AlpspiX platform, Mittenwald old town (20 min by train, painted houses, violin museum), or Innsbruck as a second-country day (1h20 by train).",
              "D8 Train Garmisch → MUC airport (~2h with one change) and fly home. Or sleep near the airport if the flight is early.",
            ],
            days10: [
              "Same spine with 4 nights Munich (add Dachau for the adults in rotation, or a Starnberger See boat day) and 5–6 nights Garmisch.",
              "Extra Garmisch days: Innsbruck (Alpine Zoo, Nordkette cable car from the city centre, Golden Roof), Mittenwald + Karwendelbahn, Oberammergau woodcarvers, a Königssee day (long — ~2.5h by car, boat to St. Bartholomä).",
              "Option: drop Garmisch for Füssen/Schwangau as the mountain base (Neuschwanstein, Forggensee, Tegelberg cable car + summer luge). Fewer trains, more castles; Garmisch has the better scenery.",
            ],
            anchorsKids: "Partnach Gorge, Zugspitze cog train, Eibsee pedal boats, Hellabrunn zoo, Kids' Kingdom, beer-garden playgrounds, Tegelberg luge (if Füssen).",
            anchorsAdults: "Zugspitze summit, Alpspitze, Mittenwald, Innsbruck, Munich museums, Dachau (rotating).",
            mayWeek: "Any May week works. Zugspitze and Eibsee cable car have had short spring maintenance windows in April/May [verify]. Alpspitzbahn usually open. Wankbahn reopens in May [verify]. Thunderstorms in the afternoon — do lifts in the morning.",
            verify: [
              "IAD–MUC nonstop days of week for May 2027",
              "Zugspitze / Eibsee cable car spring maintenance dates",
              "Neuschwanstein ticket release window and group booking rules",
              "Deutschlandticket 2027 price and tourist eligibility",
              "Garmisch Ferienhaus inventory for 7",
            ],
          },
          status: "shortlisted",
          statusReason: "Shortlisted 2026-10-03 with a detailed plan (see Plan below). The budget-friendly, car-free Alps option with a real city attached.",
        },
        {
          id: "dolomites-bolzano-ortisei",
          name: "Dolomites: Bolzano + Ortisei (leans on a car)",
          bases: "Bolzano (2–3 nights) → Ortisei / Val Gardena or Castelrotto (4–5 nights)",
          type: "mountains",
          costTier: 4,
          flightHours: 9.5,
          direct: "seasonal",
          connectionCostsDay: "no",
          flightNote: "No nonstop to the Dolomites. IAD–VCE (United, seasonal) ~9h + ~3h to Bolzano [verify]; or IAD–MUC nonstop + 4h EuroCity over the Brenner to Bolzano [verify].",
          train: "partial",
          trainHours: 1.3,
          trainNote: "Rail gets you to Bolzano (Munich–Bolzano ~4h EC; Verona–Bolzano 1h30). Bolzano–Ortisei is bus 350 via Ponte Gardena ~1h15, or 45 min by car [verify].",
          car: "needed",
          carNote: "Realistically needed in May: Alpe di Siusi, Seceda, the Gardena/Sella pass loop, Lago di Carezza and Lago di Braies all rely on lifts and seasonal shuttle buses that are mostly not running yet. 7 = 9-seater. Pass roads are fine but twisty.",
          rail: 2,
          kid3: 3,
          kid7: 4,
          scenery: 5,
          history: 3,
          beach: "no",
          beachHow: "Lake Garda (Riva del Garda) is ~2h for a lake day. Not a beach day.",
          lodgingStyle: "Bolzano hotel; Val Gardena / Castelrotto apartment or farm stay (Roter Hahn network).",
          lodging57: "Large Ferienwohnungen for 7 exist, but many Val Gardena places close between seasons in May — check availability early [verify].",
          weather: "Bolzano ~72°F, Ortisei (1,236 m) ~60°F, passes may still be snowy or closed in early May.",
          notes: "MAY REALITY: this is the Dolomites' dead season. Most lifts are closed until late May or mid-June — Seceda typically late May, Alpe di Siusi gondola from Ortisei mid/late May, Col Raiser and Dantercepies mid-June [verify 2027]. Many huts and some hotels are shut. What works: Ötzi the Iceman museum in Bolzano (a genuine kid winner), Renon/Ritten cable car + narrow-gauge train + earth pyramids (year-round), Castelrotto, Lago di Carezza by car, Alpe di Siusi by road to Compatsch (seasonal car restrictions 9–17h [verify]), valley-floor walks in Val Gardena. The honest answer for the Dolomites is 'come back in late June'.",
          openQuestions: [
            "Does anyone want the Dolomites badly enough to accept a car and closed lifts?",
            "Would late May (May 24–31) open enough to change the answer?",
          ],
          todos: [
            { text: "Pull 2027 opening dates for Seceda, Alpe di Siusi, Col Raiser", done: false },
          ],
          verify: [
            "Lift opening dates for May 2027 (Seceda, Alpe di Siusi, Col Raiser, Dantercepies)",
            "Munich–Bolzano EuroCity schedule",
            "IAD–VCE seasonal nonstop dates",
            "Accommodation open in Val Gardena in May",
          ],
          status: "idea",
          statusReason: "Weakest fit for a May + rail brief; kept for honesty and in case someone insists.",
        },
        {
          id: "france-annecy-chamonix",
          name: "France: Annecy + Chamonix",
          bases: "Annecy (4 nights) → Chamonix (3–4 nights), via Geneva",
          type: "mixed",
          costTier: 4,
          flightHours: 8.5,
          direct: "yes",
          connectionCostsDay: "no",
          flightNote: "IAD–GVA nonstop (United) ~8.5h [verify]. Annecy is 45 min from Geneva airport by bus/shuttle; Chamonix ~1h15. Fallback: IAD–CDG + TGV Paris–Annecy 3h40.",
          train: "partial",
          trainHours: 2.5,
          trainNote: "Annecy–Chamonix by rail is 2.5–3h with 1–2 changes (via La Roche-sur-Foron and Saint-Gervais, finishing on the Mont-Blanc Express) [verify]; by road it is 1h15. The rail route is scenic but slow.",
          car: "optional",
          carNote: "Annecy itself is walkable with a lakeside bike path (bike trailer for Penny). A car makes the Annecy–Chamonix leg and lake loop easy; 7 = van. Chamonix valley has good free buses and the Mont-Blanc Express.",
          rail: 3,
          kid3: 5,
          kid7: 5,
          scenery: 5,
          history: 2,
          beach: "yes",
          beachHow: "Annecy's lake 'plages' (Albigny, Impérial, Marquisats) — grassy lakeside beaches, water ~60°F in May; the kids will go in anyway.",
          lodgingStyle: "Annecy apartment (old town or lakeside); Chamonix chalet.",
          lodging57: "Chamonix chalets for 7 are plentiful and May is its quiet season — cheap and empty. Annecy 4BR is harder; two apartments or an aparthotel.",
          weather: "Annecy ~68°F, Chamonix ~60°F, May is rainy-ish; high peaks still in snow.",
          notes: "OPEN IN MAY (verify 2027): Aiguille du Midi (year-round with short spring maintenance; 'Step into the Void' box), Montenvers train + Mer de Glace ice cave (runs), Lac d'Annecy boat tours (from April), Gorges du Fier (from March), Parc de Merlet animal park (from ~May), summer luge at Chamonix (weekends from May). USUALLY NOT YET: Brévent and Flégère lifts (closed between ski season and mid-June), Tramway du Mont-Blanc (mid-June), many Chamonix restaurants/hotels in early May. Annecy: Palais de l'Isle, château, Thursday/Saturday markets, paddleboats, Semnoz. Day options: Yvoire on Lake Geneva, CERN, Geneva jet d'eau.",
          openQuestions: [
            "Is the Annecy–Chamonix rail route worth 3h for the scenery, or just drive it?",
            "Add a Paris night at either end via TGV?",
          ],
          todos: [
            { text: "Check Chamonix lift spring closure dates for 2027", done: false },
            { text: "Check IAD–GVA nonstop schedule", done: false },
          ],
          verify: [
            "IAD–GVA nonstop schedule",
            "Annecy–Chamonix rail connection and times",
            "Chamonix lift spring closures (Brévent, Flégère, Aiguille du Midi maintenance)",
          ],
          status: "idea",
          statusReason: "Annecy is a near-perfect kid town; the rail leg is the weak point.",
        },
      ],
    },

    /* ================================================================
       4. POLAND / GERMANY
       ================================================================ */
    {
      id: "poland-germany",
      name: "Poland / Germany",
      type: "city",
      costTier: 2,
      railScore: 4,
      status: "researching",
      statusReason: "Highest history/novelty and best value; hinges on the WWII-sites-with-kids question and the lack of a Poland nonstop.",
      why: "History and novelty off the charts, Poland is the best value in Europe, Berlin and Kraków are superb walking cities, and Berlin–Dresden–Prague is a scenic all-rail corridor.",
      whyNot: "No nonstop to Poland from DC; the least scenery of the four buckets; the WWII/Holocaust-site question with Penny and Simon is real and unresolved.",
      notes: "",
      openQuestions: [
        "STANDING QUESTION — How do we handle WWII/Holocaust sites with young kids: split the group (adults rotate, one stays with the kids) or skip entirely? Auschwitz-Birkenau advises against visits for children under 14; Berlin's Topography of Terror / Sachsenhausen, Munich's Dachau and Kraków's Schindler's Factory are similarly heavy. Decide this before picking a sketch.",
        "Is a one-stop connection to Poland acceptable, or does the nonstop-only preference push us to a Germany-first version?",
      ],
      todos: [
        { text: "Check whether United IAD–BER runs in May 2027", done: false },
        { text: "Check whether LOT adds a Washington route by 2027", done: false },
      ],
      subOptions: [
        {
          id: "krakow-berlin",
          name: "Kraków + Berlin",
          bases: "Berlin (4 nights) → Kraków (4 nights), or reverse",
          type: "city",
          costTier: 2,
          flightHours: 8.5,
          direct: "seasonal",
          connectionCostsDay: "no",
          flightNote: "IAD–BER nonstop (United) ~8.5h — launched 2022 and has varied by season; confirm May 2027 [verify]. Otherwise one stop via FRA/MUC. Kraków has no US nonstops.",
          train: "yes",
          trainHours: 7,
          trainNote: "Berlin–Kraków direct EuroCity via Wrocław ~7h [verify], or Berlin–Warsaw 5.5h + Warsaw–Kraków 2.5h, or a 1.5h flight. One long day train with a buffet car is fine once.",
          car: "none",
          carNote: "Not needed. Auschwitz (1h15) and Wieliczka (30 min) by tour bus or train.",
          rail: 4,
          kid3: 3,
          kid7: 4,
          scenery: 3,
          history: 5,
          beach: "no",
          beachHow: "Strandbad Wannsee in Berlin is a lake beach — novelty only in May.",
          lodgingStyle: "Apartments in Kazimierz / Old Town (Kraków) and Prenzlauer Berg / Mitte (Berlin).",
          lodging57: "Kraków 4BR apartments are plentiful and cheap — 7 is easy. Berlin big apartments exist but short-term rental rules keep tightening [verify]; aparthotels are a safe fallback.",
          weather: "Both ~66°F highs; May is one of Berlin's best months. Some rain.",
          notes: "Kraków: Wawel dragon (breathes fire on the hour), Rynek underground museum, Wieliczka salt mine (800 steps down, chapels — kids' route exists; check minimum age [verify]), Vistula boats, pierogi. Zakopane / Tatras is a 2h bus for a mountain day. Berlin: Zoo (one of the world's largest), Legoland Discovery Centre, Tiergarten, Reichstag dome (book), DDR Museum, Spree boat, Tempelhofer Feld bikes, Museum Island (Pergamon main building closed for renovation — check what's open [verify]). The Berlin Wall Memorial on Bernauer Straße is kid-tolerable; Topography of Terror and Sachsenhausen are not. Potsdam / Sanssouci day trip.",
          openQuestions: [
            "Auschwitz: adults split over two half-days, or skip?",
            "Train the whole way or fly Berlin–Kraków?",
          ],
          todos: [
            { text: "Check Berlin–Kraków EC timetable", done: false },
            { text: "Check Wieliczka minimum age for the tourist route", done: false },
          ],
          verify: [
            "IAD–BER nonstop schedule for May 2027",
            "Berlin–Kraków EuroCity timetable",
            "Wieliczka tourist-route minimum age",
            "Pergamon / Museum Island renovation status",
          ],
          status: "researching",
          statusReason: "The core of the bucket; long but doable rail leg.",
        },
        {
          id: "krakow-munich",
          name: "Kraków + Munich (fly between)",
          bases: "Munich (4 nights) → Kraków (4 nights)",
          type: "city",
          costTier: 2,
          flightHours: 8.5,
          direct: "yes",
          connectionCostsDay: "no",
          flightNote: "IAD–MUC nonstop ~8.5h [verify]. Munich–Kraków is a 1.5h flight (Lufthansa/LOT) [verify].",
          train: "no",
          trainHours: 10,
          trainNote: "Munich–Kraków by rail is 10h+ with changes via Vienna or Prague — not a sensible leg. Inserting Vienna as a third base makes it all-rail: Munich–Vienna 4h Railjet, Vienna–Kraków ~5h EC [verify].",
          car: "none",
          carNote: "Not needed in either city.",
          rail: 2,
          kid3: 4,
          kid7: 4,
          scenery: 3,
          history: 5,
          beach: "no",
          beachHow: "None.",
          lodgingStyle: "Apartments / aparthotels in both.",
          lodging57: "Kraków easy for 7; Munich 4BR scarce — aparthotel.",
          weather: "Both ~66°F, variable.",
          notes: "Pairs the easy nonstop with Poland. Munich adds the Deutsches Museum, Hellabrunn zoo and a possible Garmisch/Zugspitze day. Munich was the Nazi 'capital of the movement' — the Dachau + Auschwitz combination makes this the heaviest sketch for the WWII question. Weakest rail story in the bucket unless Vienna is added.",
          openQuestions: [
            "Insert Vienna to make it all-rail (3 bases)?",
          ],
          todos: [],
          verify: [
            "Munich–Kraków flight schedule",
            "Vienna–Kraków train times",
          ],
          status: "idea",
          statusReason: "Fails the rail-spine test unless Vienna is inserted.",
        },
        {
          id: "berlin-dresden-prague",
          name: "Berlin + Dresden (+ Prague adjacent)",
          bases: "Berlin (4 nights) → Dresden (3 nights), Prague as a 2-night tail or a long day",
          type: "city",
          costTier: 2,
          flightHours: 8.5,
          direct: "seasonal",
          connectionCostsDay: "no",
          flightNote: "IAD–BER nonstop (United) ~8.5h, confirm 2027 [verify]; else IAD–FRA nonstop + 4h ICE, or IAD–MUC. Prague has no IAD nonstop — if ending there, connect home.",
          train: "yes",
          trainHours: 2,
          trainNote: "Berlin–Dresden EC/IC ~2h hourly. Dresden–Prague EC ~2h15 along the Elbe — one of Europe's prettier rides [verify].",
          car: "none",
          carNote: "Not needed. Saxon Switzerland by S-Bahn to Kurort Rathen + ferry + 30-min uphill walk to the Bastei.",
          rail: 5,
          kid3: 4,
          kid7: 5,
          scenery: 4,
          history: 5,
          beach: "no",
          beachHow: "Berlin lakes only. No beach day.",
          lodgingStyle: "Berlin apartment / aparthotel; Dresden Neustadt apartment; Prague Old Town / Malá Strana apartment.",
          lodging57: "Dresden and Prague are cheap and spacious — 7 is easy. Berlin as above.",
          weather: "~66–68°F, some rain, long evenings.",
          notes: "Dresden: Zwinger, Frauenkirche (rebuilt after 1945), Transport Museum, Hygiene Museum children's museum, Elbe paddle steamers, Großer Garten park railway run by kids (season from April [verify]), Dresden Zoo. Saxon Switzerland: Bastei bridge and Königstein fortress — manageable for everyone. Meissen porcelain. Prague: castle, astronomical clock, Petřín funicular and mirror maze, Charles Bridge early. Berlin notes as in Kraków + Berlin. Most scenic sketch in the bucket and fully rail.",
          openQuestions: [
            "Prague as a real third base or a long day from Dresden?",
            "Fly home from Berlin (nonstop) or Prague (connection)?",
          ],
          todos: [
            { text: "Check Dresden–Prague EC timetable", done: false },
          ],
          verify: [
            "IAD–BER nonstop schedule",
            "Dresden–Prague EuroCity timetable",
            "Dresden park railway season",
            "IAD–BER nonstop operating in May 2027",
            "Berlin short-term rental rules 2027",
            "Dresden–Prague EC timetable",
            "Großer Garten park railway season",
            "Pergamon / Museum Island status",
            "PRG connection options home",
          ],
          detail: {
            arrival: "Only works as drawn if United's IAD–BER nonstop is running in May 2027 [verify]; otherwise IAD–FRA nonstop + ICE to Berlin (~4h), which is a stopover-ish arrival. Fly home from BER (nonstop) or PRG via a connection.",
            lodging: "Dresden and Prague: cheap, spacious 4–5BR apartments (Dresden Neustadt, Prague Vinohrady/Malá Strana). Berlin: apartments in Prenzlauer Berg/Mitte, subject to short-term rental rules [verify], or an aparthotel; Potsdam (25 min by S-Bahn) is a calmer base with kids and has houses.",
            days7: [
              "D1 Land BER. Tiergarten, Reichstag dome (pre-booked, evening slot is lovely), early night.",
              "D2 Berlin Zoo + Aquarium (half day), afternoon Spree boat, Museum Island exterior walk, East Side Gallery.",
              "D3 Potsdam: Sanssouci park and palaces, or Berlin Wall Memorial (Bernauer Str., kid-tolerable) + Legoland Discovery Centre + Tempelhofer Feld bikes.",
              "D4 EC/IC to Dresden (2h). Zwinger courtyard, Frauenkirche dome climb (ramps), Brühl's Terrace, Neustadt dinner.",
              "D5 Saxon Switzerland: S-Bahn to Kurort Rathen, ferry, 30-min uphill walk to the Bastei bridge; afternoon Königstein fortress or Elbe paddle steamer back.",
              "D6 Dresden: Transport Museum, Hygiene Museum children's museum, Großer Garten park railway (run by kids, from April [verify]), Dresden Zoo.",
              "D7 EC Dresden → Prague along the Elbe (2h15, left side). Long day: Castle, Charles Bridge, Petřín funicular + mirror maze, back to Dresden on the evening train — or sleep in Prague and fly home from PRG via a connection.",
              "D8 Fly home from BER (train back 2h) or PRG.",
            ],
            days10: [
              "4 nights Berlin/Potsdam, 3 nights Dresden, 3 nights Prague — a true three-base all-rail trip.",
              "Extra Berlin: Deutsches Technikmuseum (planes, trains), Spandau citadel, DDR Museum, Pergamon status [verify], Sachsenhausen/Topography of Terror for the adults in rotation.",
              "Extra Dresden: Meissen porcelain factory (45 min), Moritzburg castle (lake, horse-drawn), Pillnitz palace by paddle steamer.",
              "Prague: castle day, Vyšehrad, Vltava pedal boats, National Technical Museum, Letná park beer garden, a day in Kutná Hora (bone church — maybe adults only).",
            ],
            anchorsKids: "Zoo, Legoland Discovery, Spree boat, Bastei, paddle steamers, park railway, Petřín funicular and mirror maze, Technical Museum.",
            anchorsAdults: "Reichstag, Wall Memorial, Sanssouci, Frauenkirche, Elbe train, Prague castle and bridge.",
            mayWeek: "Any week; Berlin's best month. Dresden park railway and Elbe steamers run from spring [verify]. The WWII sites question applies here (Sachsenhausen, Topography of Terror) — the rotating-adults plan is easy because the kids' sights are dense.",
            verify: [
              "IAD–BER nonstop operating in May 2027",
              "Berlin short-term rental rules 2027",
              "Dresden–Prague EC timetable",
              "Großer Garten park railway season",
              "Pergamon / Museum Island status",
              "PRG connection options home",
            ],
          },
          status: "shortlisted",
          statusReason: "Shortlisted 2026-10-03 with a detailed plan (see Plan below). Most scenic sketch in the bucket and all-rail.",
        },
        {
          id: "warsaw-krakow",
          name: "Warsaw + Kraków",
          bases: "Warsaw (3–4 nights) → Kraków (4–5 nights)",
          type: "city",
          costTier: 1,
          flightHours: 10.5,
          direct: "no",
          connectionCostsDay: "no",
          flightNote: "No nonstop IAD–WAW; one stop via FRA/MUC/ZRH/VIE/LHR, ~10–11h total. LOT flies to JFK/EWR/ORD, not Washington — check if that changes by 2027 [verify].",
          train: "yes",
          trainHours: 2.3,
          trainNote: "EIP Pendolino Warszawa Centralna → Kraków Główny ~2h20 [verify].",
          car: "none",
          carNote: "Not needed.",
          rail: 5,
          kid3: 4,
          kid7: 5,
          scenery: 3,
          history: 5,
          beach: "no",
          beachHow: "Vistula 'beaches' in Warsaw — novelty. Gdańsk/Sopot (Baltic, 3h by train) could replace Warsaw if a beach day matters.",
          lodgingStyle: "Apartments — cheap and spacious.",
          lodging57: "7 is trivially easy in both cities.",
          weather: "~66°F, some rain.",
          notes: "Cheapest sketch on the board by far. Warsaw: Copernicus Science Centre (one of Europe's best), Łazienki Park peacocks, Warsaw Zoo, Old Town rebuilt from rubble, POLIN museum (adults), Warsaw Uprising Museum (intense; has a children's room — 7 is borderline [verify guidance]). Kraków as in Kraków + Berlin, plus Zakopane. Milk bars and pierogi are kid-easy food.",
          openQuestions: [
            "Is a connection acceptable for the cheapest, most novel option?",
            "Gdańsk instead of Warsaw for sea + Solidarity history?",
          ],
          todos: [
            { text: "Check LOT Washington plans for 2027", done: false },
          ],
          verify: [
            "Connection options IAD–WAW",
            "LOT route plans",
            "Pendolino booking window",
            "Museum age guidance (Uprising Museum, POLIN)",
          ],
          status: "idea",
          statusReason: "Best value and novelty; no nonstop.",
        },
      ],
    },
  ],

  /* Cross-cutting group decisions. status: open | decided */
  groupQuestions: [
    { id: "gq-brother", text: "Jeremy in or out? (decides 5 vs 7 → lodging type, van vs. no car)", status: "open", answer: "", due: "early 2027" },
    { id: "gq-lodging", text: "One big house vs. hotels/apartments?", status: "decided", answer: "Any format works as long as the adults have a shared living space in the evening after the kids are down (house, apartment, aparthotel suite, or two adjacent units). Hotels and separate rentals are acceptable.", due: "" },
    { id: "gq-flights", text: "Direct flights only, or connections OK? (Rules in/out Poland, Seville, the Dolomites)", status: "decided", answer: "Nonstop preferred; a connection or short stopover is fine if it lands us at base 1 the same day. Avoid losing a full day to travel.", due: "" },
    { id: "gq-budget", text: "Budget ceiling, all-in per family unit? (Cost is a tiebreaker in scoring, but a ceiling still matters)", status: "open", answer: "", due: "" },
    { id: "gq-passports", text: "Passport status for all travelers — kids' passports (5-year validity), 6-months-validity rule, ETIAS for Schengen expected by 2027 [verify], UK ETA [verify]", status: "open", answer: "", due: "" },
    { id: "gq-window", text: "Preferred May window: early / mid / late? Memorial Day is Mon May 31, 2027 — overlap or avoid?", status: "open", answer: "", due: "early 2027" },
    { id: "gq-stopover", text: "Appetite for a one-night stopover city on arrival (land, sleep, then train to base 1)?", status: "open", answer: "", due: "" },
    { id: "gq-pace", text: "Minimum nights per base? (3 nights minimum makes 7 days a strict two-base trip)", status: "decided", answer: "3 nights per base is a preference, not a rule; relax it for the right itinerary. The goal is minimizing days lost to transit.", due: "" },
  ],

  /* Dated entries for anything ruled in or out. */
  decisionLog: [
    { id: "log-1", date: "2026-10-03", text: "Set up the comparison site with four buckets and 16 itinerary sketches.", reason: "Shape and rank now so the final pick is quick once dates and headcount land in early 2027." },
    { id: "log-2", date: "2026-10-03", text: "Scoring weights: rail, kid appeal, scenery/towns and history/novelty high; travel time and beach medium; cost near zero.", reason: "Cost is a tiebreaker, not a constraint." },
    { id: "log-3", date: "2026-10-03", text: "Lodging format decided: any format works if the adults have a shared living space in the evening after the kids are down (house, apartment, aparthotel suite, or two adjacent units). Hotels and separate rentals are acceptable.", reason: "Evening adult time is the real requirement; the house-vs-hotel label was a proxy for it." },
    { id: "log-4", date: "2026-10-03", text: "Flights decided: nonstop preferred, but a connection or short stopover is fine if it lands us at base 1 the same day.", reason: "The thing to avoid is losing a full day to travel, not the connection itself. Opens up Poland, Seville and Austria." },
    { id: "log-5", date: "2026-10-03", text: "Pace decided: 3 nights per base is a preference, not a rule; relax it for the right itinerary.", reason: "The goal is minimizing days lost to transit, which three-base rail trips can still achieve." },
    { id: "log-6", date: "2026-10-03", text: "Shortlisted five sketches with detailed plans: Lisbon + Porto, London + Edinburgh + Highlands by rail, Lucerne + Berner Oberland, Munich + Garmisch, Berlin + Dresden (+ Prague).", reason: "These are the ones worth planning day by day; the rest stay as ideas or research." },
    { id: "log-7", date: "2026-10-03", text: "Expanded the shortlist to ten: added day-by-day plans for Seville + Granada (or Cádiz), Barcelona + Girona / Costa Brava, London + Edinburgh, Lisbon + Algarve, Austria: Salzburg + Salzkammergut.", reason: "The public shortlist page shows the top ten by score, and every sketch on it needs a plan the family can read." },
  ],
};
